# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11DCXFFgVjETV86oQl4vttEkuyDr2JjbC
"""

import numpy as np
import pandas as pd
from scipy.interpolate import interp1d

SEQUENCE_LENGTH = 100
AUG_PER_SEQ = 5


def load_sequences(file):
    df = pd.read_csv(file)
    data = df.iloc[:, 1:-1].values
    label = df.iloc[0, -1]

    sequences = []
    for i in range(0, len(data), SEQUENCE_LENGTH):
        seq = data[i:i+SEQUENCE_LENGTH]
        if len(seq) == SEQUENCE_LENGTH:
            sequences.append(seq)

    return sequences, label


def time_warp(seq):
    t_original = np.linspace(0, 1, SEQUENCE_LENGTH)
    scale = np.random.uniform(0.8, 1.2)

    t_new = np.linspace(0, 1, int(SEQUENCE_LENGTH * scale))
    warped = []

    for i in range(seq.shape[1]):
        f = interp1d(t_original, seq[:, i], fill_value="extrapolate")
        temp = f(t_new)

        f2 = interp1d(np.linspace(0,1,len(temp)), temp)
        temp = f2(t_original)

        warped.append(temp)

    return np.stack(warped, axis=1)


def augment_sequence(seq):
    aug = seq.astype(np.float32)

    flex = aug[:, :4]
    imu = aug[:, 4:]

    # 🔹 flex variation
    flex += np.random.normal(0, 5, flex.shape)

    # 🔹 stronger IMU variation
    imu += np.random.normal(0, 800, imu.shape)

    scale = np.random.uniform(0.5, 1.5)
    imu *= scale

    drift = np.random.normal(0, 300, (1, imu.shape[1]))
    imu += drift

    imu += np.random.normal(0, 200, imu.shape)

    combined = np.concatenate([flex, imu], axis=1)
    combined = time_warp(combined)

    imu = combined[:, 4:]
    imu = np.clip(imu, -20000, 20000)

    combined[:, 4:] = imu

    return combined


def generate_augmented(input_file, output_file):
    sequences, label = load_sequences(input_file)
    all_data = []

    for seq in sequences:
        for row in seq:
            all_data.append(list(row) + [label])

        for _ in range(AUG_PER_SEQ):
            aug_seq = augment_sequence(seq)
            for row in aug_seq:
                all_data.append(list(row) + [label])

    columns = [
        "flex1","flex2","flex3","flex4",
        "ax","ay","az","gx","gy","gz",
        "label"
    ]

    pd.DataFrame(all_data, columns=columns).to_csv(output_file, index=False)

    print("Saved:", output_file)


# RUN
generate_augmented("1.csv", "aug_1_strong.csv")
generate_augmented("3.csv", "aug_3_strong.csv")
generate_augmented("Hi.csv", "aug_hi_strong.csv")

model = Sequential([
    Input(shape=(100, 10)),

    LSTM(64,
         return_sequences=True,
         activation='tanh',
         recurrent_activation='sigmoid'),

    Dropout(0.3),

    LSTM(64,
         activation='tanh',
         recurrent_activation='sigmoid'),

    Dropout(0.3),

    Dense(64, activation='relu'),
    Dense(y_cat.shape[1], activation='softmax')
])

for i in range(10):
    seq = np.expand_dims(X_test[i], axis=0)
    pred = model.predict(seq)

    predicted = le.inverse_transform([np.argmax(pred)])[0]
    actual = le.inverse_transform([np.argmax(y_test[i])])[0]

    print(i, "Pred:", predicted, "| Actual:", actual)

import numpy as np
import pandas as pd

SEQUENCE_LENGTH = 100

def generate_none_sequence():
    flex = np.ones((SEQUENCE_LENGTH, 4)) * 1023

    imu = np.random.normal(0, 150, (SEQUENCE_LENGTH, 6))

    # drift
    drift = np.linspace(0, np.random.uniform(-300, 300), SEQUENCE_LENGTH).reshape(-1,1)
    imu += drift

    # tiny motion
    t = np.linspace(0, 2*np.pi, SEQUENCE_LENGTH)
    imu[:, 0] += 300 * np.sin(t)
    imu[:, 1] += 250 * np.cos(t)

    # small spikes
    for _ in range(np.random.randint(1, 4)):
        idx = np.random.randint(0, SEQUENCE_LENGTH)
        imu[idx] += np.random.normal(0, 800, 6)

    imu = np.clip(imu, -20000, 20000)

    return np.concatenate([flex, imu], axis=1)


def generate_none_dataset(num_sequences=12):
    all_data = []

    for _ in range(num_sequences):
        seq = generate_none_sequence()
        for row in seq:
            all_data.append(list(row) + ["NONE"])

    columns = [
        "flex1","flex2","flex3","flex4",
        "ax","ay","az","gx","gy","gz",
        "label"
    ]

    df = pd.DataFrame(all_data, columns=columns)
    df.to_csv("none.csv", index=False)

    print("Saved none.csv with", num_sequences, "sequences")


# RUN
generate_none_dataset(12)

import tensorflow as tf

# load trained model
model = tf.keras.models.load_model("sign_model_final.keras")

# convert
converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.optimizations = [tf.lite.Optimize.DEFAULT]

tflite_model = converter.convert()

# save
with open("sign_model.tflite", "wb") as f:
    f.write(tflite_model)

print("TFLite model saved")

import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout, Input
from tensorflow.keras.utils import to_categorical

SEQUENCE_LENGTH = 100


# 🔹 LOAD DATA
def load_data(files):
    X, y = [], []

    for file in files:
        df = pd.read_csv(file)

        data = df.iloc[:, :-1].values.astype(np.float32)
        labels = df.iloc[:, -1].values

        for i in range(0, len(data), SEQUENCE_LENGTH):
            seq = data[i:i+SEQUENCE_LENGTH]
            if len(seq) == SEQUENCE_LENGTH:
                X.append(seq)
                y.append(labels[i])

    return np.array(X), np.array(y)


files = [
    "aug_1_strong.csv",
    "aug_3_strong.csv",
    "aug_hi_strong.csv",
    "none.csv"
]

X, y = load_data(files)

print("Shape:", X.shape)
print("Classes:", set(y))


# 🔹 NORMALIZATION
mean = X.mean(axis=(0,1))
std = X.std(axis=(0,1)) + 1e-6
X = (X - mean) / std


# 🔹 LABEL ENCODING
le = LabelEncoder()
y_encoded = le.fit_transform(y)
y_cat = to_categorical(y_encoded)

print("Encoded:", le.classes_)


# 🔹 SHUFFLE
indices = np.arange(len(X))
np.random.shuffle(indices)

X = X[indices]
y_cat = y_cat[indices]


# 🔹 SPLIT
split = int(0.8 * len(X))

X_train, X_test = X[:split], X[split:]
y_train, y_test = y_cat[:split], y_cat[split:]


# 🔥 MODEL (TFLITE COMPATIBLE — VERY IMPORTANT)
model = Sequential([
    Input(shape=(100, 10)),

    LSTM(64,
         return_sequences=True,
         activation='tanh',
         recurrent_activation='sigmoid',
         unroll=True),

    Dropout(0.3),

    LSTM(64,
         activation='tanh',
         recurrent_activation='sigmoid',
         unroll=True),

    Dropout(0.3),

    Dense(64, activation='relu'),
    Dense(y_cat.shape[1], activation='softmax')
])


# 🔹 CLASS WEIGHTS
class_weights = {
    0: 1.0,   # 1
    1: 1.0,   # 3
    2: 1.5,   # HI (boost)
    3: 0.7    # NONE (reduce dominance)
}


model.compile(
    optimizer=tf.keras.optimizers.Adam(0.001),
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

model.summary()


# 🔹 TRAIN
model.fit(
    X_train, y_train,
    validation_data=(X_test, y_test),
    epochs=25,
    batch_size=16,
    class_weight=class_weights
)


# 🔹 EVALUATE
loss, acc = model.evaluate(X_test, y_test)
print("Test Accuracy:", acc)


# 🔹 SAVE EVERYTHING
model.save("sign_model_final.keras")
np.save("mean.npy", mean)
np.save("std.npy", std)

print("Saved model + normalization")

import tensorflow as tf

model = tf.keras.models.load_model("sign_model_final.keras")

converter = tf.lite.TFLiteConverter.from_keras_model(model)

tflite_model = converter.convert()

with open("sign_model.tflite", "wb") as f:
    f.write(tflite_model)

print("SUCCESS")

import os
os.environ["CUDA_VISIBLE_DEVICES"] = "-1"  # 🔥 FORCE CPU (CRITICAL)

import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout, Input
from tensorflow.keras.utils import to_categorical

SEQUENCE_LENGTH = 100


def load_data(files):
    X, y = [], []

    for file in files:
        df = pd.read_csv(file)

        data = df.iloc[:, :-1].values.astype(np.float32)
        labels = df.iloc[:, -1].values

        for i in range(0, len(data), SEQUENCE_LENGTH):
            seq = data[i:i+SEQUENCE_LENGTH]
            if len(seq) == SEQUENCE_LENGTH:
                X.append(seq)
                y.append(labels[i])

    return np.array(X), np.array(y)


files = [
    "aug_1_strong.csv",
    "aug_3_strong.csv",
    "aug_hi_strong.csv",
    "none.csv"
]

X, y = load_data(files)

# NORMALIZATION
mean = X.mean(axis=(0,1))
std = X.std(axis=(0,1)) + 1e-6
X = (X - mean) / std

# LABELS
le = LabelEncoder()
y_encoded = le.fit_transform(y)
y_cat = to_categorical(y_encoded)

# SHUFFLE
indices = np.arange(len(X))
np.random.shuffle(indices)
X, y_cat = X[indices], y_cat[indices]

# SPLIT
split = int(0.8 * len(X))
X_train, X_test = X[:split], X[split:]
y_train, y_test = y_cat[:split], y_cat[split:]


# 🔥 MODEL (SAFE LSTM)
model = Sequential([
    Input(shape=(100, 10)),

    LSTM(64, return_sequences=True,
         activation='tanh',
         recurrent_activation='sigmoid'),

    Dropout(0.3),

    LSTM(64,
         activation='tanh',
         recurrent_activation='sigmoid'),

    Dropout(0.3),

    Dense(64, activation='relu'),
    Dense(y_cat.shape[1], activation='softmax')
])

model.compile(
    optimizer=tf.keras.optimizers.Adam(0.001),
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

model.fit(
    X_train, y_train,
    validation_data=(X_test, y_test),
    epochs=25,
    batch_size=16
)

model.save("sign_model_final.keras")
np.save("mean.npy", mean)
np.save("std.npy", std)

print("Training complete")

print(mean.tolist())
print(std.tolist())